import { test, expect } from '@playwright/test'
test('algorithm menu uses the dark palette and supports keyboard and outside dismissal', async ({ page }) => {
  await page.goto('./?algorithm=spanning-tree')
  const picker = page.getByRole('combobox', { name: 'Search algorithm' })
  await expect(picker).toBeEnabled({ timeout: 60000 })
  await picker.click()
  const menu = page.getByRole('listbox', { name: 'Search algorithms' })
  await expect(menu).toHaveCSS('background-color', 'rgb(16, 32, 26)')
  await expect(page.getByRole('option', { name: 'Spanning tree', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.screenshot({ path: `test-results/algorithm-menu-${test.info().project.name}.png` })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('option', { name: 'Dijkstra', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'dijkstra/1')
  await expect(picker).toBeEnabled(); await picker.click()
  await picker.press('Escape'); await expect(menu).toHaveCount(0); await expect(picker).toBeFocused()
  await picker.press('ArrowDown'); await picker.press('Home'); await picker.press('Enter')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'dijkstra/1')
  await expect(menu).toHaveCount(0)
  await expect(picker).toBeEnabled(); await picker.click()
  await page.locator('main.map').click({ position: { x: 20, y: 20 } })
  await expect(menu).toHaveCount(0)
})
