import { test, expect } from '@playwright/test'
test.setTimeout(90000)

test('ambient retreats without trapping touch or keyboard controls, and Escape restores the study', async ({ page, isMobile }) => {
  await page.clock.install()
  await page.goto('./'); await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Ambient', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'replay', { timeout: 45000 })
  const controls = page.locator('.ambient-controls'), header = page.locator('.header-tools'), map = page.locator('main.map')
  await page.clock.fastForward(4100)
  await expect(controls).toHaveCSS('opacity', '0')
  await expect(header).toHaveCSS('opacity', '0')
  await expect(page.getByRole('combobox', { name: 'Country', exact: true, includeHidden: true })).toBeHidden()
  await expect(page.locator('.route-caption')).toBeVisible()
  await expect(page.locator('.ambient-algorithm')).toHaveText('Dijkstra')
  await expect(page.getByRole('link', { name: '© OpenStreetMap contributors · ODbL' })).toBeVisible()
  if (isMobile) await map.tap({ position: { x: 100, y: 200 } })
  else await page.mouse.move(100, 200)
  await expect(controls).toHaveCSS('opacity', '1')
  await map.focus()
  await page.clock.fastForward(4100)
  await expect(controls).toHaveCSS('opacity', '0')
  await page.keyboard.press('Tab')
  // Check focus protection directly in the touch project as well as the
  // desktop project's native Tab traversal.
  if (isMobile) await page.getByRole('button', { name: 'Pause sequence' }).focus()
  await expect(page.getByRole('button', { name: 'Pause sequence' })).toBeFocused()
  await expect(controls).toHaveCSS('opacity', '1')
  await page.clock.fastForward(4500)
  await expect(controls).toHaveCSS('opacity', '1')
  await page.keyboard.press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-running', 'false')
  await map.focus(); await page.clock.fastForward(4500)
  await expect(controls).toHaveCSS('opacity', '1')
  await page.getByRole('button', { name: 'Resume sequence' }).click()
  await page.getByText('About', { exact: true }).click()
  await map.focus()
  await page.clock.fastForward(4100)
  await expect(controls).toHaveCSS('opacity', '0')
  await expect(header).toHaveCSS('opacity', '1')
  await expect(page.locator('.about')).toHaveAttribute('open', '')
  await page.keyboard.press('Escape')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'off')
  await expect(map).toBeFocused()
  await expect(page.getByRole('combobox', { name: 'Start place' })).toBeVisible()
  await expect(page.getByRole('slider', { name: 'Search replay' })).toBeVisible()
  await expect(page.getByText('About this study', { exact: true })).toBeVisible()
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'off')
})

test('ambient binds genuine journeys, reuses loaded chunks, and exits into the current study', async ({ page }) => {
  const errors: string[] = [], music: string[] = [], chunks: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (request.url().endsWith('.m4a')) music.push(request.url()); if (request.url().endsWith('.bin.gz.bin')) chunks.push(request.url()) })
  await page.goto('./'); await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Ambient', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'replay', { timeout: 45000 })
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'dijkstra/1')
  const slider = page.getByRole('slider', { name: 'Search replay', includeHidden: true })
  const duration = Number(await slider.getAttribute('max')); expect(duration).toBeGreaterThanOrEqual(25); expect(duration).toBeLessThanOrEqual(65)
  await expect(page.getByRole('combobox', { name: 'Start place', includeHidden: true })).toBeHidden()
  await page.locator('main.map').focus(); await page.keyboard.press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-running', 'false')
  const description = await slider.getAttribute('aria-valuetext'), event = description!.match(/; (\d+) recorded events/)![1]
  await expect(page.locator('canvas')).toHaveAttribute('data-event', event)
  await page.waitForTimeout(250)
  await expect(page.locator('canvas')).toHaveAttribute('data-event', event!)
  await page.keyboard.press('End'); await page.keyboard.press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'hold')
  const first = await page.locator('.route-caption').textContent()
  chunks.length = 0
  await page.getByRole('button', { name: 'Next journey' }).press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'replay', { timeout: 45000 })
  expect(await page.locator('.route-caption').textContent()).not.toBe(first)
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'bidirectional-dijkstra/1')
  expect(chunks).toEqual([])
  await page.getByRole('button', { name: 'Exit ambient' }).press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'off')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Replay duration' })).toHaveValue('30')
  await expect(page.locator('main.map')).toHaveCSS('opacity', '1')
  await expect(page.getByRole('combobox', { name: 'Search algorithm' })).toHaveValue('bidirectional')
  expect(music).toEqual([]); expect(errors).toEqual([])
})

test('reduced-motion ambient presents completed stills and requires explicit Next', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.goto('./')
  await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('combobox', { name: 'Search algorithm' }).selectOption('astar')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'astar/1')
  await page.getByRole('button', { name: 'Ambient', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'still', { timeout: 45000 })
  await expect(page.locator('.ambient-controls')).toHaveCSS('opacity', '1')
  await expect(page.locator('.study')).toHaveAttribute('data-progress', '1')
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'complete')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'astar/1')
  const first = await page.locator('.route-caption').textContent()
  await page.waitForTimeout(300); await expect(page.locator('.route-caption')).toHaveText(first!)
  await page.getByRole('button', { name: 'Next journey' }).press('Space')
  await expect(page.locator('.route-caption')).not.toHaveText(first!, { timeout: 45000 })
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'still')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'bidirectional-astar/1')
  await page.getByRole('button', { name: 'Next journey' }).press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'greedy-best-first/1', { timeout: 45000 })
  await expect(page.locator('.greedy-note')).toHaveText('Shortest route not guaranteed')
  await page.getByRole('button', { name: 'Next journey' }).press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'dijkstra/1', { timeout: 45000 })
  await page.getByRole('button', { name: 'Next journey' }).press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'multisource-dijkstra/1', { timeout: 45000 })
  await page.getByRole('button', { name: 'Next journey' }).press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'bidirectional-dijkstra/1', { timeout: 45000 })
  await page.getByRole('button', { name: 'Exit ambient' }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-progress', '1')
})

test('sequence pause suspends one continuous score; hidden return needs explicit actions', async ({ page }) => {
  await page.clock.install()
  await page.addInitScript(() => {
    const Native = AudioContext, contexts: AudioContext[] = []; let starts = 0
    Object.assign(window, { ambientAudio: { contexts, get starts() { return starts } } })
    window.AudioContext = class extends Native {
      constructor(options?: AudioContextOptions) { super(options); contexts.push(this) }
      createBufferSource() { const source = super.createBufferSource(), start = source.start.bind(source); source.start = (...args: Parameters<AudioBufferSourceNode['start']>) => { starts++; start(...args) }; return source }
    }
  })
  await page.goto('./'); await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Sound', exact: true }).press('Space')
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'on')
  await expect.poll(() => page.evaluate(() => (window as any).ambientAudio.starts)).toBe(2)
  await page.getByRole('button', { name: 'Ambient', exact: true }).press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'replay', { timeout: 45000 })
  await page.clock.fastForward(4100)
  await expect(page.locator('.ambient-controls')).toHaveCSS('opacity', '0')
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'on')
  // Native keyboard activation exercises audio gestures without pointer hit-test races.
  const pause = page.getByRole('button', { name: 'Pause sequence' })
  await pause.focus(); await expect(pause).toBeFocused()
  await expect(page.locator('.ambient-controls')).toHaveCSS('opacity', '1')
  await pause.press('Space')
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'paused')
  await expect.poll(() => page.evaluate(() => (window as any).ambientAudio.contexts[0].state)).toBe('suspended')
  await page.getByRole('button', { name: 'Resume sequence' }).press('Space')
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'on')
  await page.getByRole('button', { name: 'Next journey' }).press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'replay', { timeout: 45000 })
  expect(await page.evaluate(() => (window as any).ambientAudio.contexts.length)).toBe(1)
  expect(await page.evaluate(() => (window as any).ambientAudio.starts)).toBe(2)
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange')) })
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'off')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-running', 'false')
  await page.evaluate(() => { delete (document as any).hidden; document.dispatchEvent(new Event('visibilitychange')) })
  await page.getByRole('button', { name: 'Resume sequence' }).press('Space')
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'off')
  await page.getByRole('button', { name: 'Sound', exact: true }).press('Space')
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'on')
  await page.getByRole('button', { name: 'Exit ambient' }).press('Space')
  expect(await page.evaluate(() => (window as any).ambientAudio.contexts.length)).toBe(1)
  expect(await page.evaluate(() => (window as any).ambientAudio.starts)).toBe(2)
})
