import { test, expect } from '@playwright/test'
test.setTimeout(150000)

test('ambient plays genuine distance-paced journeys, freezes transitions and exits into the current study', async ({ page }) => {
  const errors: string[] = [], music: string[] = [], chunks: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (request.url().endsWith('.m4a')) music.push(request.url()); if (request.url().endsWith('.bin.gz.bin')) chunks.push(request.url()) })
  await page.goto('./'); await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Ambient', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'replay', { timeout: 45000 })
  const slider = page.getByRole('slider', { name: 'Search replay', includeHidden: true })
  const duration = Number(await slider.getAttribute('max')); expect(duration).toBeGreaterThanOrEqual(25); expect(duration).toBeLessThanOrEqual(65)
  await expect(page.getByRole('combobox', { name: 'Start place', includeHidden: true })).toBeHidden()
  await page.locator('main.map').focus(); await page.keyboard.press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-running', 'false')
  const description = await slider.getAttribute('aria-valuetext'), event = description!.match(/; (\d+) recorded events/)![1]
  await expect(page.locator('canvas')).toHaveAttribute('data-event', event)
  await page.waitForTimeout(250)
  await expect(page.locator('canvas')).toHaveAttribute('data-event', event!)
  await page.keyboard.press('End'); await page.keyboard.press('Space')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'hold')
  const first = await page.locator('.route-caption').textContent()
  const km = Number(first!.match(/([\d.]+) km/)![1])
  expect(Math.abs(duration - Math.min(65, Math.max(25, 30 * Math.sqrt(km / 100))))).toBeLessThan(.02)
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'fade', { timeout: 10000 })
  await page.getByRole('button', { name: 'Pause sequence', exact: true }).click()
  const opacity = await page.locator('main.map').evaluate(el => el.style.opacity)
  await page.waitForTimeout(250); expect(await page.locator('main.map').evaluate(el => el.style.opacity)).toBe(opacity)
  chunks.length = 0
  await page.getByRole('button', { name: 'Resume sequence', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'replay', { timeout: 45000 })
  expect(await page.locator('.route-caption').textContent()).not.toBe(first)
  expect(chunks).toEqual([])
  await page.getByRole('button', { name: 'Exit ambient' }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'off')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Replay duration' })).toHaveValue('30')
  await expect(page.locator('main.map')).toHaveCSS('opacity', '1')
  expect(music).toEqual([]); expect(errors).toEqual([])
})

test('reduced-motion ambient presents completed stills and requires explicit Next', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.goto('./')
  await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Ambient', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'still', { timeout: 45000 })
  await expect(page.locator('.study')).toHaveAttribute('data-progress', '1')
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'complete')
  const first = await page.locator('.route-caption').textContent()
  await page.waitForTimeout(300); await expect(page.locator('.route-caption')).toHaveText(first!)
  await page.getByRole('button', { name: 'Next journey' }).click()
  await expect(page.locator('.route-caption')).not.toHaveText(first!, { timeout: 45000 })
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'still')
  await page.getByRole('button', { name: 'Exit ambient' }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-progress', '1')
})

test('sequence pause suspends one continuous score; hidden return needs explicit actions', async ({ page }) => {
  await page.addInitScript(() => {
    const Native = AudioContext, contexts: AudioContext[] = []; let starts = 0
    Object.assign(window, { ambientAudio: { contexts, get starts() { return starts } } })
    window.AudioContext = class extends Native {
      constructor(options?: AudioContextOptions) { super(options); contexts.push(this) }
      createBufferSource() { const source = super.createBufferSource(), start = source.start.bind(source); source.start = (...args: Parameters<AudioBufferSourceNode['start']>) => { starts++; start(...args) }; return source }
    }
  })
  await page.goto('./'); await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Sound', exact: true }).click()
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'on')
  await expect.poll(() => page.evaluate(() => (window as any).ambientAudio.starts)).toBe(2)
  await page.getByRole('button', { name: 'Ambient', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'replay', { timeout: 45000 })
  await page.getByRole('button', { name: 'Pause sequence' }).click()
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'paused')
  await expect.poll(() => page.evaluate(() => (window as any).ambientAudio.contexts[0].state)).toBe('suspended')
  await page.getByRole('button', { name: 'Resume sequence' }).click()
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'on')
  await page.getByRole('button', { name: 'Next journey' }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'replay', { timeout: 45000 })
  expect(await page.evaluate(() => (window as any).ambientAudio.contexts.length)).toBe(1)
  expect(await page.evaluate(() => (window as any).ambientAudio.starts)).toBe(2)
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange')) })
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'off')
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-running', 'false')
  await page.evaluate(() => { delete (document as any).hidden; document.dispatchEvent(new Event('visibilitychange')) })
  await page.getByRole('button', { name: 'Resume sequence' }).click()
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'off')
  await page.getByRole('button', { name: 'Sound', exact: true }).click()
  await expect(page.locator('.sound-control')).toHaveAttribute('data-sound', 'on')
  await page.getByRole('button', { name: 'Exit ambient' }).click()
  expect(await page.evaluate(() => (window as any).ambientAudio.contexts.length)).toBe(1)
  expect(await page.evaluate(() => (window as any).ambientAudio.starts)).toBe(2)
})
