import { selectAlgorithm } from './algorithm-picker.ts'
import { test, expect, type Page } from '@playwright/test'

test.setTimeout(90000)
async function seek(page: Page, time: number) {
  const slider = page.getByRole('slider', { name: 'Search replay' })
  await slider.fill(String(time))
  const event = (await slider.getAttribute('aria-valuetext'))!.match(/; (\d+) recorded events/)![1]
  await expect(page.locator('canvas')).toHaveAttribute('data-event', event)
}

test('A* reveals a real goal-directed search, restores paused frames and preserves the route across mode changes', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('./')
  await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await seek(page, 30)
  const canvas = page.locator('canvas')
  const outlines = page.getByRole('button', { name: 'Show border and lake outlines' })
  await outlines.click()
  await selectAlgorithm(page, 'astar')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'astar/1')
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-goal-directed', 'true')
  await expect(outlines).toHaveAttribute('aria-pressed', 'false')
  await seek(page, 15)
  const halfway = await page.getByTestId('examined-count').textContent()
  await page.screenshot({ path: `test-results/astar-search-${test.info().project.name}.png` })
  await seek(page, 30)
  await expect(page.locator('.route-caption')).toContainText('262.7 km')
  await seek(page, 15)
  await expect(page.getByTestId('examined-count')).toHaveText(halfway!)
  await expect(canvas).toHaveAttribute('data-route-phase', 'hidden')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(canvas).toHaveAttribute('data-route-phase', 'hidden')
  await expect(canvas).toHaveAttribute('data-route-energy', '0')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await selectAlgorithm(page, 'bidirectional')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'bidirectional-dijkstra/1')
  await expect(canvas).toHaveAttribute('data-goal-directed', 'false')
  await expect(canvas).toHaveAttribute('data-outlines', 'hidden')
  await expect(page.locator('.route-caption')).toContainText('262.7 km')
  await selectAlgorithm(page, 'astar')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'astar/1')
  await expect(page.locator('.study')).toHaveAttribute('data-progress', '1')
  await expect(canvas).toHaveAttribute('data-goal-directed', 'true')
  await expect(canvas).toHaveAttribute('data-route-energy', '0')
  await selectAlgorithm(page, 'dijkstra')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'dijkstra/1')
  await expect(canvas).toHaveAttribute('data-goal-directed', 'false')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
