import { selectAlgorithm } from './algorithm-picker.ts'
import { test, expect } from '@playwright/test'
test('breadth-first replays real traversal, seeks reversibly and shares its mode', async ({ page }) => {
 test.setTimeout(90000)
 const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
 await page.goto('./?algorithm=breadth-first')
 await expect(page.locator('.study')).toHaveAttribute('data-algorithm','breadth-first/1',{timeout:45000})
 await page.getByRole('button',{name:'Pause',exact:true}).click()
 const slider=page.getByRole('slider',{name:'Search replay'})
 await slider.fill('15'); await expect(page.locator('.search-tip')).toBeHidden()
 const count=await page.getByTestId('examined-count').textContent()
 await page.screenshot({path:`test-results/breadth-first-${test.info().project.name}.png`})
 await slider.fill('30'); await expect(page.locator('.search-tip')).toBeHidden()
 await expect(page.locator('.replay-status')).toHaveText('Fewest-connection route found')
 await expect(page.locator('.greedy-note')).toHaveText('Fewest connections · shortest distance not guaranteed')
 await slider.fill('15'); await expect(page.getByTestId('examined-count')).toHaveText(count!)
 await selectAlgorithm(page, 'dijkstra')
 await expect(page.locator('.study')).toHaveAttribute('data-algorithm','dijkstra/1')
 expect(errors).toEqual([])
})
