import { test, expect } from '@playwright/test'
test.setTimeout(90000)

test('greedy displays real coral exploration, reversible replay and an honest first-found route', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('./?algorithm=greedy')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'greedy-best-first/1', { timeout: 45000 })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const canvas = page.locator('canvas'), slider = page.getByRole('slider', { name: 'Search replay' })
  await expect(canvas).toHaveAttribute('data-greedy', 'true')
  await expect(canvas).toHaveAttribute('data-goal-directed', 'true')
  await expect(page.locator('.greedy-note')).toHaveText('Shortest route not guaranteed')
  await slider.fill('15')
  await expect(page.locator('.search-tip')).toBeVisible()
  expect(Number(await canvas.getAttribute('data-focus-event'))).toBeGreaterThan(0)
  const halfway = await page.getByTestId('examined-count').textContent()
  await expect(canvas).toHaveAttribute('data-route-phase', 'hidden')
  await page.screenshot({ path: `test-results/greedy-search-${test.info().project.name}.png` })
  await slider.fill('30')
  await expect(page.locator('.search-tip')).toBeHidden()
  await expect(page.locator('.replay-status')).toHaveText('Greedy route found')
  await expect(canvas).toHaveAttribute('data-route-phase', 'complete')
  const greedyKm = parseFloat((await page.locator('.route-caption em').textContent())!)
  await page.screenshot({ path: `test-results/greedy-route-${test.info().project.name}.png` })
  await slider.fill('15')
  await expect(page.getByTestId('examined-count')).toHaveText(halfway!)
  await expect(canvas).toHaveAttribute('data-route-phase', 'hidden')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(canvas).toHaveAttribute('data-route-energy', '0')
  await page.getByRole('combobox', { name: 'Search algorithm' }).selectOption('dijkstra')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'dijkstra/1')
  await expect(canvas).toHaveAttribute('data-greedy', 'false')
  await expect(page.locator('.greedy-note')).toHaveCount(0)
  await expect(page.locator('.route-caption')).toContainText('262.7 km')
  expect(greedyKm).toBeGreaterThanOrEqual(262.7)
  await page.getByRole('combobox', { name: 'Search algorithm' }).selectOption('greedy')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'greedy-best-first/1')
  await expect(canvas).toHaveAttribute('data-route-energy', '0')
  await expect(page).toHaveURL(/algorithm=greedy/)
  await page.reload()
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'greedy-best-first/1', { timeout: 45000 })
  await expect(page.getByRole('combobox', { name: 'Search algorithm' })).toHaveValue('greedy')
  await expect(page.locator('.greedy-note')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('greedy naturally ends the search and reveals its route before resting', async ({ page }) => {
  await page.goto('./?algorithm=greedy&duration=5')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'greedy-best-first/1', { timeout: 45000 })
  // Replay caps each frame's time step. Slow software-rendered CI hosts can
  // take longer than five wall-clock seconds; exercise the natural endpoint
  // from its final segment instead of timing the whole search animation.
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Replay duration' })).toHaveValue('5')
  await page.getByRole('slider', { name: 'Search replay' }).fill('4.5')
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'hidden')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'revealing', { timeout: 30000 })
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'complete', { timeout: 30000 })
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await expect(page.locator('.greedy-note')).toBeVisible()
})
