import { test, expect, type Page } from '@playwright/test'

test.setTimeout(120000)
async function openPaused(page: Page) {
  await page.goto('./')
  await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
}
async function time(page: Page, seconds: number) {
  const slider = page.getByRole('slider', { name: 'Search replay' })
  await expect(slider).toHaveValue(String(seconds))
  const event = (await slider.getAttribute('aria-valuetext'))!.match(/; (\d+) recorded events/)![1]
  await expect(page.locator('canvas')).toHaveAttribute('data-event', event)
}

test('map shortcuts play once, scrub real events and respect duration', async ({ page }) => {
  const errors: string[] = [], musicRequests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (request.url().endsWith('.m4a')) musicRequests.push(request.url()) })
  await openPaused(page)
  const map = page.getByRole('main'), slider = page.getByRole('slider', { name: 'Search replay' })
  await page.getByRole('button', { name: 'Search', exact: true }).focus()
  await page.keyboard.press('Tab'); await expect(map).toBeFocused()
  await page.keyboard.press('Home'); await time(page, 0)
  await page.keyboard.down('Space')
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.keyboard.down('Space')
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.keyboard.up('Space'); await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  const paused = await slider.inputValue()
  await page.waitForTimeout(150); await expect(slider).toHaveValue(paused)
  await slider.fill('10'); await map.focus(); await time(page, 10)
  const counts = await page.getByTestId('examined-count').textContent()
  await page.keyboard.press('ArrowRight'); await time(page, 11)
  await page.keyboard.press('ArrowLeft'); await time(page, 10)
  await expect(page.getByTestId('examined-count')).toHaveText(counts!)
  await page.keyboard.press('Shift+ArrowRight'); await time(page, 15)
  await page.keyboard.press('Shift+ArrowLeft'); await time(page, 10)
  await page.keyboard.press('Control+ArrowRight'); await time(page, 10)
  await page.keyboard.press('Home'); await page.keyboard.press('ArrowLeft'); await time(page, 0)
  await page.keyboard.press('End'); await page.keyboard.press('ArrowRight'); await time(page, 30)
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'complete')
  for (const duration of [120, 5]) {
    await page.getByRole('combobox', { name: 'Replay duration' }).selectOption(String(duration))
    await map.focus(); await page.keyboard.press('Home'); await time(page, 0)
    await page.keyboard.press('ArrowRight'); await time(page, 1)
    await page.keyboard.press('Shift+ArrowRight'); await time(page, Math.min(6, duration))
  }
  expect(musicRequests).toEqual([]); expect(errors).toEqual([])
})

test('timeline shortcuts work without doubling native input and preserve other controls and busy states', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await openPaused(page)
  const slider = page.getByRole('slider', { name: 'Search replay' }), map = page.getByRole('main')
  await slider.fill('10'); await slider.focus()
  await page.keyboard.press('ArrowRight'); await time(page, 11)
  await page.keyboard.press('ArrowLeft'); await time(page, 10)
  await page.keyboard.press('Shift+ArrowRight'); await time(page, 15)
  await page.keyboard.press('Shift+ArrowLeft'); await time(page, 10)
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await slider.fill('10')
  const play = page.getByRole('button', { name: 'Play', exact: true })
  await play.focus(); await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await slider.fill('10')
  await page.getByRole('combobox', { name: 'Destination place' }).focus()
  await page.keyboard.press('ArrowRight'); await page.keyboard.press('ArrowLeft'); await time(page, 10)
  const about = page.getByText('About this study', { exact: true })
  await about.focus(); await page.keyboard.press('Space')
  await expect(page.locator('.about')).toHaveAttribute('open', '')
  await page.keyboard.press('ArrowRight'); await time(page, 10)
  await page.keyboard.press('Space'); await expect(page.locator('.about')).not.toHaveAttribute('open')
  const sound = page.getByRole('button', { name: 'Sound', exact: true })
  await sound.focus(); await page.keyboard.press('Space')
  const volume = page.getByRole('slider', { name: 'Music volume' })
  await expect(volume).toBeVisible(); await volume.focus(); await page.keyboard.press('ArrowRight')
  await expect(volume).toHaveValue('51'); await time(page, 10)
  await sound.focus(); await page.keyboard.press('Space')
  await expect(sound).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Choose start on map' }).click()
  await map.focus(); await page.keyboard.press('Space'); await page.keyboard.press('ArrowRight'); await time(page, 10)
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('combobox', { name: 'Country', exact: true }).selectOption('uk')
  await expect(page.getByRole('dialog')).toBeVisible()
  await map.focus(); await page.keyboard.press('Space'); await page.keyboard.press('ArrowRight'); await time(page, 10)
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Country', exact: true })).toHaveValue('ch')
  // Hold a real second query before it enters the worker, then release it.
  await page.evaluate(() => {
    const post = Worker.prototype.postMessage
    Worker.prototype.postMessage = function(message: any, options: any) {
      if (message.type === 'search') (window as any).releaseSearch = () => post.call(this, message, options)
      else post.call(this, message, options)
    }
  })
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Computing…', exact: true })).toBeDisabled()
  await map.focus(); await page.keyboard.press('Space'); await page.keyboard.press('ArrowRight')
  await expect(slider).toHaveValue('10')
  await page.evaluate(() => (window as any).releaseSearch())
  await expect(page.getByRole('button', { name: 'Search', exact: true })).toBeEnabled()
  expect(errors).toEqual([])
})
