import { test, expect } from '@playwright/test'
test.setTimeout(90000)
async function seek(page: import('@playwright/test').Page, value: number) {
  await page.getByRole('slider', { name: 'Search replay' }).fill(String(value))
  await expect(page.locator('.study')).toHaveAttribute('data-progress', String(value / 30))
  const description = await page.getByRole('slider', { name: 'Search replay' }).getAttribute('aria-valuetext')
  const event = description!.match(/; (\d+) recorded events/)![1]
  await expect(page.locator('canvas')).toHaveAttribute('data-event', event)
}
test('national search, reverse seeking and another pair of endpoints', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()) })
  await page.goto('./')
  await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await seek(page, 0)
  await expect(page.getByTestId('settled-count')).toHaveText('0')
  await page.screenshot({ path: `test-results/start-${test.info().project.name}.png` })
  const blankMap = await page.locator('canvas').screenshot()
  const outlineRegion = { x: 0, y: 180, width: page.viewportSize()!.width, height: 150 }
  const outlineImage = await page.screenshot({ clip: outlineRegion })
  const outlines = page.getByRole('button', { name: 'Show border and lake outlines' })
  await expect(outlines).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('canvas')).toHaveAttribute('data-outlines', 'visible')
  await outlines.click()
  await expect(page.locator('canvas')).toHaveAttribute('data-outlines', 'hidden')
  expect((await page.screenshot({ clip: outlineRegion })).equals(outlineImage)).toBe(false)
  await expect(page.getByTestId('settled-count')).toHaveText('0')
  await outlines.click()
  await expect(page.locator('canvas')).toHaveAttribute('data-outlines', 'visible')
  expect((await page.screenshot({ clip: outlineRegion })).equals(outlineImage)).toBe(true)
  await seek(page, 15)
  const halfway = await page.getByTestId('examined-count').textContent()
  expect(Number(halfway?.replace(/[^0-9]/g, ''))).toBeGreaterThan(100000)
  await page.screenshot({ path: `test-results/search-${test.info().project.name}.png` })
  expect((await page.locator('canvas').screenshot()).equals(blankMap)).toBe(false)
  await seek(page, 30)
  await expect(page.getByText('Route found', { exact: true })).toBeVisible()
  await expect(page.locator('.route-caption')).toContainText('262.7 km')
  await page.screenshot({ path: `test-results/route-${test.info().project.name}.png` })
  await seek(page, 15)
  await expect(page.getByTestId('examined-count')).toHaveText(halfway!)
  await page.getByRole('combobox', { name: 'Start place' }).selectOption('Basel')
  await page.getByRole('combobox', { name: 'Destination place' }).selectOption('Lugano')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.locator('.route-caption')).toContainText('Basel', { timeout: 20000 })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await seek(page, 30)
  await expect(page.locator('.route-caption')).toContainText('Lugano')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
test('a missing chunk prevents searching and retry loads the complete record', async ({ page }) => {
  await page.route('**/nodes-000-*.bin.gz.bin', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('./')
  await expect(page.getByRole('alert')).toContainText('incomplete graph cannot be searched', { timeout: 20000 })
  await expect(page.getByRole('button', { name: 'Search', exact: true })).toBeDisabled()
  await page.unroute('**/nodes-000-*.bin.gz.bin')
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
})
test('reduced motion opens the completed trace without autoplay', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.goto('./')
  await expect(page.locator('.study')).toHaveAttribute('data-progress', '1', { timeout: 45000 })
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'complete')
  await expect(page.locator('canvas')).toHaveAttribute('data-route-progress', '1')
  await expect(page.locator('canvas')).toHaveAttribute('data-route-energy', '0')
  await expect(page.getByRole('link', { name: /OpenStreetMap contributors/ })).toBeVisible()
})
test('the completed route reveals, pauses and settles without advancing search events', async ({ page }) => {
  await page.goto('./')
  await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await seek(page, 29.97)
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'hidden')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.getByText('Revealing the route', { exact: true })).toBeVisible()
  await expect.poll(async () => Number(await page.locator('canvas').getAttribute('data-route-progress'))).toBeGreaterThan(.08)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(page.getByText('Route reveal paused', { exact: true })).toBeVisible()
  const event = await page.locator('canvas').getAttribute('data-event')
  const progress = await page.locator('canvas').getAttribute('data-route-progress')
  const examined = await page.getByTestId('examined-count').textContent()
  const partialRoute = await page.locator('canvas').screenshot()
  await page.screenshot({ path: `test-results/route-reveal-${test.info().project.name}.png` })
  await page.waitForTimeout(250)
  await expect(page.locator('canvas')).toHaveAttribute('data-route-progress', progress!)
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.getByText('Route found', { exact: true })).toBeVisible({ timeout: 30000 })
  await expect(page.locator('canvas')).toHaveAttribute('data-route-progress', '1')
  await expect(page.locator('canvas')).toHaveAttribute('data-route-energy', '0')
  await expect(page.locator('canvas')).toHaveAttribute('data-event', event!)
  await expect(page.getByTestId('examined-count')).toHaveText(examined!)
  expect((await page.locator('canvas').screenshot()).equals(partialRoute)).toBe(false)
  await seek(page, 15)
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'hidden')
  await seek(page, 30)
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'complete')
  await expect(page.locator('canvas')).toHaveAttribute('data-route-energy', '0')
  await seek(page, 29.97)
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.getByText('Revealing the route', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Replay search from the beginning' }).click()
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'hidden')
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await seek(page, 29.97)
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.getByText('Revealing the route', { exact: true })).toBeVisible()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('canvas')).toHaveAttribute('data-route-phase', 'complete')
  await expect(page.locator('canvas')).toHaveAttribute('data-route-energy', '0')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
})
