import { test, expect } from '@playwright/test'
test.setTimeout(120000)

test('ambient introduces three real territories, shares their sources and returns to journey controls', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('./')
  await expect(page.locator('.study')).toHaveAttribute('data-state', 'ready', { timeout: 45000 })
  await page.getByRole('button', { name: 'Ambient', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'still', { timeout: 45000 })
  for (const algorithm of ['bidirectional-dijkstra/1', 'astar/1', 'bidirectional-astar/1', 'multisource-dijkstra/1']) {
    await page.getByRole('button', { name: 'Next journey' }).click()
    await expect(page.locator('.study')).toHaveAttribute('data-algorithm', algorithm, { timeout: 45000 })
    await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'still')
  }
  const canvas = page.locator('canvas')
  await expect(canvas).toHaveAttribute('data-source-count', '3')
  await expect(canvas).toHaveAttribute('data-territory-complete', 'true')
  await expect(canvas).toHaveAttribute('data-route-phase', 'hidden')
  await expect(canvas).toHaveAttribute('data-meeting-event', '0')
  await expect(page.locator('.map-marker')).toHaveCount(3)
  await expect(page.getByRole('combobox', { name: 'Search algorithm' })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Start place' })).toHaveCount(0)
  await expect(page.locator('.replay-status')).toHaveText('Territories complete')
  await expect(page).toHaveURL(/source-c=.*algorithm=multisource/)
  const url = page.url(), caption = await page.locator('.route-caption').textContent()
  expect(caption).not.toContain('→'); expect(caption).not.toContain(' km')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `test-results/territories-complete-${test.info().project.name}.png` })
  await page.getByRole('button', { name: 'Exit ambient' }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-ambient-phase', 'off')
  await expect(canvas).toHaveAttribute('data-source-count', '3')
  await page.reload()
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'multisource-dijkstra/1', { timeout: 45000 })
  for (const key of ['from', 'to', 'source-c']) expect(new URL(page.url()).searchParams.get(key)).toBe(new URL(url).searchParams.get(key))
  await expect(canvas).toHaveAttribute('data-source-count', '3')
  await page.getByRole('button', { name: 'Journey', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'dijkstra/1', { timeout: 45000 })
  await expect(canvas).toHaveAttribute('data-source-count', '0')
  await expect(page.getByRole('combobox', { name: 'Start place' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Search algorithm' })).toHaveValue('dijkstra')
  expect(errors).toEqual([])
})

test('territories replay genuine events forward and backward, then hold without route animation', async ({ page }) => {
  await page.goto('./?from=geneve&to=zurich&source-c=lugano&algorithm=multisource&duration=5')
  const canvas = page.locator('canvas')
  await expect(page.locator('.study')).toHaveAttribute('data-algorithm', 'multisource-dijkstra/1', { timeout: 45000 })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const slider = page.getByRole('slider', { name: 'Search replay' })
  await slider.fill('2.5')
  const count = await page.getByTestId('examined-count').textContent()
  await expect(canvas).toHaveAttribute('data-territory-complete', 'false')
  await page.screenshot({ path: `test-results/territories-search-${test.info().project.name}.png` })
  await slider.fill('5')
  await expect(canvas).toHaveAttribute('data-territory-complete', 'true')
  await expect(canvas).toHaveAttribute('data-route-phase', 'hidden')
  await slider.fill('2.5')
  await expect(page.getByTestId('examined-count')).toHaveText(count!)
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('.study')).toHaveAttribute('data-progress', '1', { timeout: 15000 })
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await expect(canvas).toHaveAttribute('data-route-phase', 'hidden')
})
