import { test, expect } from '@playwright/test'
test('estimated time retains distance, model labels and reversible replay', async ({page})=>{
 test.setTimeout(90000)
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('./?objective=time')
 await expect(page.locator('.study')).toHaveAttribute('data-algorithm','dijkstra/1',{timeout:45000})
 await page.getByRole('button',{name:'Pause',exact:true}).click()
 const slider=page.getByRole('slider',{name:'Search replay'})
 await slider.fill('15');const count=await page.getByTestId('examined-count').textContent()
 await slider.fill('30');await expect(page.locator('.replay-status')).toHaveText('Fastest modelled route found')
 await expect(page.locator('.greedy-note')).toContainText('no traffic or junction delays')
 await expect(page.locator('.route-caption em')).toContainText('min)')
 await expect(page.locator('.route-caption em')).toContainText('km')
 await slider.fill('15');await expect(page.getByTestId('examined-count')).toHaveText(count!)
 await page.getByRole('combobox',{name:'Search algorithm'}).selectOption('astar')
 await expect(page.locator('.study')).toHaveAttribute('data-algorithm','astar/1')
 await expect(page.locator('canvas')).toHaveAttribute('data-time-emphasis','true')
 await page.getByRole('slider',{name:'Search replay'}).fill('15')
 await page.screenshot({path:`test-results/time-astar-${test.info().project.name}.png`})
 await expect(page.getByRole('button',{name:'Estimated time',exact:true})).toHaveAttribute('aria-pressed','true')
 await expect(page).toHaveURL(/objective=time/)
 await page.getByRole('button',{name:'Distance',exact:true}).click()
 await expect(page.locator('.study')).toHaveAttribute('data-algorithm','astar/1')
 await expect(page.locator('.greedy-note')).toHaveCount(0)
 await expect(page.locator('canvas')).toHaveAttribute('data-time-emphasis','false')
 await page.getByRole('combobox',{name:'Search algorithm'}).selectOption('breadth-first')
 await expect(page.locator('.study')).toHaveAttribute('data-algorithm','breadth-first/1')
 await expect(page.getByRole('button',{name:'Distance',exact:true})).toBeDisabled()
 await expect(page.getByRole('button',{name:'Estimated time',exact:true})).toBeDisabled()
 expect(errors).toEqual([])
})
