import type { Point } from './search/contracts.ts'
import { PLACES } from './places.ts'
import { SWISS_POOL, UK_POOL, AMBIENT_POOLS, type AmbientPool } from './ambient/pools.ts'
export interface Country {
  id: string; name: string; manifest: string; identity: string; places: Point[]
  outlines: boolean; large: boolean; downloadMB: number; snapshot: string; deviceNote?: string
  ambient: AmbientPool; outlineDescription: string; outlineCredit: string; outlineCreditUrl: string
}
// An app release selects immutable records. The browser never follows “latest”.
export const COUNTRIES: Country[] = [
  { id: 'ch', name: 'Switzerland', manifest: './data/pfad/ch-20260929-6a17f71de78c/manifest.json', identity: '6a17f71de78c6a9883f333e39ee27c5ddfc1657bded4ede92842549004b0908e', places: PLACES, ambient: SWISS_POOL, outlineDescription: 'Switzerland’s border from swissBOUNDARIES3D (2026-01), and lake shorelines from the FOEN Vector25 reference network (2007).', outlineCredit: '© swisstopo, FOEN', outlineCreditUrl: 'https://www.swisstopo.admin.ch/en/terms-of-use-free-geodata-and-geoservices', outlines: true, large: false, downloadMB: 16, snapshot: '29 Sep 2026' },
  { id: 'uk', name: 'United Kingdom', manifest: 'https://motionstudies.app/pfad-data/uk-20260929-0555cf638ba1/manifest.json', identity: '0555cf638ba1cc246e741531c406e9a32a651b3c75b2a842f77f2fdbdfe7f909', ambient: UK_POOL, outlineDescription: 'United Kingdom coastline and land border, with major lake shorelines, from a pinned Natural Earth 1:10m reference snapshot.', outlineCredit: 'Natural Earth · public domain', outlineCreditUrl: 'https://www.naturalearthdata.com/about/terms-of-use/', outlines: true, large: true, downloadMB: 93, deviceNote: 'The complete graph needs around 1–2 GB of browser memory, plus graphics memory. Tested on desktop; phone support is still unverified.', snapshot: '29 Sep 2026', places: [
    { name: 'London', lon: -.1276, lat: 51.5072 }, { name: 'Edinburgh', lon: -3.1883, lat: 55.9533 },
    { name: 'Manchester', lon: -2.2426, lat: 53.4808 }, { name: 'Birmingham', lon: -1.8904, lat: 52.4862 },
    { name: 'Cardiff', lon: -3.1791, lat: 51.4816 }, { name: 'Glasgow', lon: -4.2518, lat: 55.8642 },
    { name: 'Belfast', lon: -5.9301, lat: 54.5973 }, { name: 'Bristol', lon: -2.5879, lat: 51.4545 },
    { name: "Land's End", lon: -5.714, lat: 50.066 }, { name: "John o’ Groats", lon: -3.069, lat: 58.638 },
  ] },
  {"id": "is", "name": "Iceland", "manifest": "https://motionstudies.app/pfad-data/is-20260930-ad6c30aac073/manifest.json", "identity": "ad6c30aac073a816465eb9cb1f4d6f92aace87387cb702ebd96266b557619990", "outlines": true, "large": false, "downloadMB": 1.5, "snapshot": "30 Sep 2026", "outlineDescription": "Country outline from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.is, places: AMBIENT_POOLS.is.places },
  {"id": "nz", "name": "New Zealand", "manifest": "https://motionstudies.app/pfad-data/nz-20260930-7bbcde863f2e/manifest.json", "identity": "7bbcde863f2ec5a31d478a4e13513385649c07225b28f609aea402578e9c21db", "outlines": true, "large": false, "downloadMB": 9.3, "snapshot": "30 Sep 2026", "outlineDescription": "New Zealand coastline and major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.nz, places: AMBIENT_POOLS.nz.places },
  {"id": "lu", "name": "Luxembourg", "manifest": "https://motionstudies.app/pfad-data/lu-20260930-e04927d2555c/manifest.json", "identity": "e04927d2555c1ae98a15b022f30308a983e9596951c4dad64bc703ffcb0c1626", "outlines": true, "large": false, "downloadMB": 1.0, "snapshot": "30 Sep 2026", "outlineDescription": "Country outline from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.lu, places: AMBIENT_POOLS.lu.places },
  {"id": "nl", "name": "Netherlands", "manifest": "https://motionstudies.app/pfad-data/nl-20260930-40fbb64d05c2/manifest.json", "identity": "40fbb64d05c268e91d65f285b1bd7951ac02500fa1919b24f8b8a250db31ade7", "outlines": true, "large": false, "downloadMB": 22.2, "snapshot": "30 Sep 2026", "outlineDescription": "European Netherlands coastline and land border, with major lake shorelines, from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.nl, places: AMBIENT_POOLS.nl.places },
  {"id": "ie", "name": "Ireland", "manifest": "https://motionstudies.app/pfad-data/ie-20260930-ec1382418ea4/manifest.json", "identity": "ec1382418ea473b3c8908b102e0f2db3f3fb9493d83270db87213fcd8135c7dd", "outlines": true, "large": false, "downloadMB": 20.4, "snapshot": "30 Sep 2026", "outlineDescription": "The whole island of Ireland, including Northern Ireland: one joined coastline and major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.ie, places: AMBIENT_POOLS.ie.places },
  {"id": "sc", "name": "Scandinavia", "manifest": "https://motionstudies.app/pfad-data/sc-20260930-0718a55b5352/manifest.json", "identity": "0718a55b53520565a42cc38cb99c0183e75a6da4c36b2423c5b1496541d6a6b6", "outlines": true, "large": true, "downloadMB": 77.9, "snapshot": "30 Sep 2026", "deviceNote": "A complete graph of Norway, Sweden and Denmark. Memory use is comparable to the UK study; physical-phone stability remains unverified.", "outlineDescription": "Mainland Norway, Sweden and Denmark with coastal islands: one joined coastline and major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.sc, places: AMBIENT_POOLS.sc.places },
  {"id": "pl", "name": "Poland", "manifest": "https://motionstudies.app/pfad-data/pl-20260930-404c5b1ce2d0/manifest.json", "identity": "404c5b1ce2d0870823d97e3e7b6c0f26072f3a99f1c3e15034c8c161e12a246c", "outlines": true, "large": true, "downloadMB": 59.6, "snapshot": "30 Sep 2026", "deviceNote": "The complete road graph needs substantial browser and graphics memory. Tested in desktop browsers and a mobile WebKit viewport; physical-phone stability remains unverified.", "outlineDescription": "Poland’s land border and major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.pl, places: AMBIENT_POOLS.pl.places },
  {"id": "it", "name": "Italy", "manifest": "https://motionstudies.app/pfad-data/it-20260930-423f3384f3a6/manifest.json", "identity": "423f3384f3a6923335b6933ab1388245edc7429e5a947f191dee9d43d5465639", "outlines": true, "large": true, "downloadMB": 85.3, "snapshot": "30 Sep 2026", "deviceNote": "The complete road graph needs substantial browser and graphics memory. Tested in desktop browsers and a mobile WebKit viewport; physical-phone stability remains unverified.", "outlineDescription": "Italy’s coastline and land border, including Sicily and Sardinia, with major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.it, places: AMBIENT_POOLS.it.places },
  {"id": "es", "name": "Spain", "manifest": "https://motionstudies.app/pfad-data/es-20260930-044eacc93968/manifest.json", "identity": "044eacc9396880ce1f92b4c160629763e54341f3a1114c0eeb531c5105d3865d", "outlines": true, "large": true, "downloadMB": 59.0, "snapshot": "30 Sep 2026", "deviceNote": "The complete Geofabrik European Spain graph needs substantial browser and graphics memory. Physical-phone stability remains unverified.", "outlineDescription": "Spain’s coastline and land border, with major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.es, places: AMBIENT_POOLS.es.places },
  {"id": "fr", "name": "France", "manifest": "https://motionstudies.app/pfad-data/fr-20260930-6edd1a545b54/manifest.json", "identity": "6edd1a545b54087424151237d4cf39403641f7716955e83dc67b2d996091995b", "outlines": true, "large": true, "downloadMB": 151.9, "snapshot": "30 Sep 2026", "deviceNote": "A complete metropolitan-France graph with over ten million routing nodes. Tested in desktop browsers and a mobile WebKit viewport; physical-phone stability remains unverified.", "outlineDescription": "Metropolitan France including Corsica, with coastline, land borders and major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.fr, places: AMBIENT_POOLS.fr.places },
  {"id": "de", "name": "Germany", "manifest": "https://motionstudies.app/pfad-data/de-20260929-083582060611/manifest.json", "identity": "08358206061146a9950e97708e3f48a8c2095c537948a688f792802a59371555", "outlines": true, "large": true, "downloadMB": 140.9, "snapshot": "29 Sep 2026", "deviceNote": "A complete graph with over ten million routing nodes. Tested in desktop browsers and a mobile WebKit viewport; physical-phone stability remains unverified.", "outlineDescription": "Germany’s land border and coastline, with major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.de, places: AMBIENT_POOLS.de.places },
  {"id": "at", "name": "Austria", "manifest": "https://motionstudies.app/pfad-data/at-20260930-f66d15dd279a/manifest.json", "identity": "f66d15dd279a28a8de052bd4e577dc5f0b078abedc3e7e2ff6a036dad443621f", "outlines": true, "large": false, "downloadMB": 23.3, "snapshot": "30 Sep 2026", "outlineDescription": "Austria’s land border and major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.at, places: AMBIENT_POOLS.at.places },
  {"id": "au", "name": "Australia", "manifest": "https://motionstudies.app/pfad-data/au-20261002-72975ec9fdfa/manifest.json", "identity": "72975ec9fdfa019f772f8ec7ae20ce91556f342d786ebe7ed871a286b4767f8e", "outlines": true, "large": true, "downloadMB": 44.6, "snapshot": "2 Oct 2026", "deviceNote": "The complete Australian road graph needs substantial browser and graphics memory. Tested on desktop; physical-phone stability remains unverified.", "outlineDescription": "Australia’s coastline, including Tasmania and mapped offshore islands, with major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.au, places: AMBIENT_POOLS.au.places },
  {"id": "sea", "name": "Southeast Asia", "manifest": "https://motionstudies.app/pfad-data/sea-20261002-eecf8c542fab/manifest.json", "identity": "eecf8c542fabeec3cd8ecf2e33bac7666764ea14390b34b478eb0cbaa66c356f", "outlines": true, "large": true, "downloadMB": 116.5, "snapshot": "2 Oct 2026", "deviceNote": "Myanmar, Thailand, Cambodia, Laos, Peninsular Malaysia and Singapore. Desktop measurements used about 2.2 GB of browser memory, plus graphics memory; physical-phone stability remains unverified.", "outlineDescription": "Joined coastline and outer land border for Myanmar, Thailand, Cambodia, Laos, Peninsular Malaysia and Singapore, with major lakes, from a pinned Natural Earth 1:10m reference snapshot. Malaysian Borneo and Brunei are excluded.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.sea, places: AMBIENT_POOLS.sea.places },
  {"id": "sa", "name": "Southern Africa", "manifest": "https://motionstudies.app/pfad-data/sa-20261002-a9718f49cf14/manifest.json", "identity": "a9718f49cf14137b2cf75ece27760b2bb1106d7a2270eda13a4dea15c7341d61", "outlines": true, "large": true, "downloadMB": 110.7, "snapshot": "2 Oct 2026", "deviceNote": "A complete graph of eleven countries, including Tanzania. Tested on desktop; substantial browser and graphics memory is required, and physical-phone stability remains unverified.", "outlineDescription": "Joined coastline and outer land borders of eleven countries, including Tanzania, with major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.sa, places: AMBIENT_POOLS.sa.places },
  {"id": "sam", "name": "South America", "manifest": "https://motionstudies.app/pfad-data/sam-20261002-c47bad2cdf2e/manifest.json", "identity": "c47bad2cdf2e04b63ce35642c2c6bdb66c88ab82bcbfed4064cf92121998e140", "outlines": true, "large": true, "downloadMB": 143.1, "snapshot": "2 Oct 2026", "deviceNote": "Nine countries: Argentina, Bolivia, Chile, Colombia, Ecuador, Paraguay, Peru, Uruguay and Venezuela. The complete graph needs substantial browser and graphics memory; physical-phone support remains unverified.", "outlineDescription": "Joined coastlines and land borders of the nine-country study, including Chile’s Easter Island, with major lake shorelines from a pinned Natural Earth 1:10m reference snapshot.", "outlineCredit": "Natural Earth · public domain", "outlineCreditUrl": "https://www.naturalearthdata.com/about/terms-of-use/", ambient: AMBIENT_POOLS.sam, places: AMBIENT_POOLS.sam.places },
]
